# Generated by Django 4.2.6 on 2024-02-15 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otoiawase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='件名')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間')),
                ('username', models.CharField(max_length=32, verbose_name='お名前')),
                ('mailadd', models.EmailField(max_length=100, verbose_name='メールアドレス')),
                ('text', models.TextField(max_length=400, verbose_name='お問い合わせ内容')),
                ('delete_TF', models.BooleanField(default=False, verbose_name='解決判断用コード')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='件名')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間')),
                ('username', models.CharField(max_length=32, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Toukou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='名前')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間')),
                ('text', models.TextField(max_length=400, verbose_name='本文')),
                ('thread_id', models.IntegerField(verbose_name='スレッドID')),
                ('toukou_id', models.IntegerField(verbose_name='投稿ID')),
                ('delete_TF', models.BooleanField(default=False, verbose_name='削除判断用コード')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
