# Generated by Django 4.2.6 on 2024-02-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eightch', '0002_remove_toukou_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toukou',
            name='profile_image',
        ),
    ]
