# Generated by Django 4.2.6 on 2024-02-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightch', '0003_remove_toukou_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toukou',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
